import { Player, defaultEquipment } from './types';

// Helper function to infer grade from existing data or default
const getGrade = (name: string, existingData: Record<string, any>): string => {
  const match = existingData[name];
  return match?.grade || '-';
};

// Helper function to infer position from existing data or default
const getPosition = (name: string, existingData: Record<string, any>): string => {
  const match = existingData[name];
  return match?.position || '';
};

// Helper function to infer height/weight from existing data or default
const getHeight = (name: string, existingData: Record<string, any>): string => {
  const match = existingData[name];
  return match?.height || '-';
};

const getWeight = (name: string, existingData: Record<string, any>): string => {
  const match = existingData[name];
  return match?.weight || '-';
};

// Existing player data for reference (from previous list)
const existingPlayers: Record<string, any> = {
  'Andrew M. Aaron': { grade: 'Sr.', position: 'SS, WR' },
  'Tyler R. Andrus': { grade: 'Sr.', position: 'OL', height: "5'11\"", weight: '240 lbs' },
  'Riley R. Averett': { grade: 'Sr.', position: 'WR, CB' },
  'Corbin D. Bauerle': { grade: 'Sr.', position: 'SB, SS', height: "5'10\"", weight: '170 lbs' },
  'Brady J. Belliston': { grade: 'Sr.', position: 'FS' },
  'Ocean T. Bishop': { grade: 'Sr.', position: 'SB, CB', height: "6'0\"", weight: '170 lbs' },
  'Luke O. Broadbent': { grade: 'Sr.' },
  'Robert M. Christensen': { grade: 'Sr.', position: 'G, C', height: "6'3\"" },
  'Cason K. Davis': { grade: 'Jr.', position: 'C, T', height: "5'8\"", weight: '230 lbs' },
  'Ryan J. Dawson': { grade: 'Sr.', position: 'G', height: "5'9\"" },
  'David B. Dean': { grade: 'Sr.', position: 'WR' },
  'Maxon J. DeGroot': { grade: 'Sr.' },
  'Owen D. Gardner': { grade: 'Sr.' },
  'Sawyer R. Hayward': { grade: 'Sr.', position: 'DE, DT' },
  'Madden S. Jensen': { grade: 'Sr.', position: 'RB', height: "6'0\"", weight: '190 lbs' },
  'Maxwell A. Larson': { grade: 'Sr.' },
  'Kaedin J. Laursen': { grade: 'Sr.', position: 'C, G' },
  'Ziah A. Leung-Wai': { grade: 'Fr.', position: 'WR, S', height: "5'10\"", weight: '160 lbs' },
  'Zackary S. Lewis': { grade: 'Fr.', position: 'TE, LB', height: "5'11\"", weight: '160 lbs' },
  'Madden S. Mack': { grade: 'So.', position: 'OL', height: "6'2\"", weight: '220 lbs' },
  'Derek R. Manning': { grade: 'Sr.', position: 'CB', height: "5'9\"" },
  'Kapono R. Manuela': { grade: 'Sr.', position: 'QB, WR', height: "5'11\"", weight: '155 lbs' },
  'Gunner B. Michaelis': { grade: 'Sr.', position: 'WR' },
  'Mitt Palmer': { grade: 'Sr.', height: "5'11\"" },
  'Jett J. Prestwich': { grade: 'Sr.' },
  'Beckham B. Rees': { grade: 'Sr.', position: 'WR, SS', height: "5'10\"" },
  'Jack Reutzel': { grade: 'Sr.' },
  'Talon K. Roberts': { grade: 'Jr.', position: 'NG, T' },
  'Jackson K. Theobald.': { grade: 'Sr.', position: 'CB', height: "6'0\"", weight: '165 lbs' },
  'Carson A. Thorne': { grade: 'Sr.', position: 'T, DT', height: "6'4\"" },
  'Bodee N. Bond': { grade: 'So.' },
  'Trigg A. Camberlango': { grade: 'So.', position: 'WR, C', height: "5'8\"", weight: '155 lbs' },
  'Preston J. Fairbanks': { grade: 'So.', position: 'WR', height: "6'0\"", weight: '170 lbs' },
  'Manatua J. Fano': { grade: 'Jr.', position: 'DL', height: "6'3\"", weight: '230 lbs' },
  'Ty Holmstead': { grade: 'So.', position: 'WR', height: "6'3\"", weight: '180 lbs' },
  'Cash T. Talese': { grade: 'So.' },
  'Ty M. Wilson': { grade: 'So.', position: 'LB', height: "6'1\"", weight: '195 lbs' },
  'Levi E. Woods': { grade: '-' },
  'Dalin N. Afu': { grade: 'Jr.', position: 'DE, DT', height: "6'2\"", weight: '235 lbs' },
  'Prince Afu': { grade: 'Sr.', position: 'RB', height: "5'11\"", weight: '190 lbs' },
  'Blake H. Averett': { grade: 'Jr.', position: 'LB', height: "5'11\"", weight: '160 lbs' },
  'Noah H. Behm': { grade: 'Jr.', position: 'SS, WR', height: "5'11\"", weight: '170 lbs' },
  'Matthew A. Bowen': { grade: 'Jr.', position: 'T, G', height: "5'10\"" },
  'Mason R. Brooks': { grade: 'Jr.', height: "5'11\"", weight: '165 lbs' },
  'Braylon T. Carroll': { grade: 'Jr.', position: 'WR', height: "6'1\"", weight: '175 lbs' },
  'Nathan B. Childs': { grade: 'Jr.', position: 'QB, WR', height: "6'3\"", weight: '165 lbs' },
  'Collin J. Christensen': { grade: 'Jr.', position: 'T, G', height: "6'3\"" },
  'Zachary D. Cowie': { grade: 'Jr.', position: 'TE, WR', height: "6'2\"", weight: '185 lbs' },
  'Logan R. Giles': { grade: 'Jr.', position: 'MLB, OLB', height: "5'11\"", weight: '190 lbs' },
  'Drew Greenwood': { grade: 'Jr.', position: 'SB, WR', height: "6'3\"", weight: '190 lbs' },
  'Dayton C. Hansen': { grade: 'Jr.', position: 'WR', height: "5'7\"", weight: '140 lbs' },
  'Nathan S. Higley': { grade: 'Jr.', position: 'DL', height: "6'0\"", weight: '300 lbs' },
  'Joshua C. Jackson': { grade: 'Jr.', position: 'TE' },
  'Rhett Jensen': { grade: 'Jr.', position: 'WR, FS' },
  'Carter J. Jorgenson': { grade: 'Jr.', position: 'RB', height: "5'10\"", weight: '160 lbs' },
  'Dylan S. Latu': { grade: 'Jr.', position: 'DL', height: "6'0\"", weight: '225 lbs' },
  'Eikipeavale T. Mausia.': { grade: 'Jr.', position: 'DL', height: "6'0\"", weight: '245 lbs' },
  'Lincoln M. Miller': { grade: 'Jr.', position: 'SS, FS', height: "6'4\"", weight: '180 lbs' },
  'Jaybian-Damani V. Na\'a': { grade: 'Sr.', position: 'NG, DT', height: "6'2\"" },
  'Mathew Nelson': { grade: 'Jr.', position: 'FS, SS', height: "5'10\"", weight: '150 lbs' },
  'Mason T. Petersen': { grade: 'Jr.', height: "5'10\"", weight: '165 lbs' },
  'Owen T. Peterson': { grade: 'Jr.', position: 'SS, WR', height: "5'8\"", weight: '155 lbs' },
  'Parker L. Pulley': { grade: 'Jr.', position: 'WR, CB', height: "5'10\"", weight: '162 lbs' },
  'Hayden D. Reutzel': { grade: 'Jr.', position: 'WR, CB' },
  'Mack T. Segura': { grade: 'Jr.', position: 'RB, FS' },
  'Hudson B. Taylor': { grade: 'Jr.', position: 'T, G' },
  'Samson N. Thompson': { grade: 'Jr.', position: 'OLB, RB' },
  'Ryker F. Tippets': { grade: 'Sr.', position: 'WR', height: "6'1\"", weight: '160 lbs' },
  'Tuapasi A. Uluilakepa Jr': { grade: 'Jr.', position: 'G, DT', height: "6'0\"", weight: '243 lbs' },
  'Latani H. Vaki': { grade: 'Jr.' },
  'Luke S. Vernon': { grade: 'Jr.', position: 'MLB, OLB', height: "6'0\"", weight: '175 lbs' },
  'Xander D. Voeller': { grade: 'Jr.', position: 'OL, OG', height: "5'11\"", weight: '225 lbs' },
  'Damian C. Wilkinson': { grade: 'Jr.', position: 'WR, S', height: "5'9\"", weight: '175 lbs' },
  'Talon J. Willardson': { grade: 'Jr.', position: 'QB, SS', height: "6'0\"", weight: '175 lbs' },
  'Jace Worthington': { grade: 'Jr.', position: 'K', height: "5'11\"", weight: '165 lbs' },
};

export const initialPlayers: Omit<Player, 'id'>[] = [
  // Period 1 (Sec 001) - 38 students
  { name: "Andrew M. Aaron", studentId: "9364997", period: "Period 1", grade: getGrade("Andrew M. Aaron", existingPlayers), position: getPosition("Andrew M. Aaron", existingPlayers), height: getHeight("Andrew M. Aaron", existingPlayers), weight: getWeight("Andrew M. Aaron", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Tyler R. Andrus", studentId: "9322546", period: "Period 1", grade: getGrade("Tyler R. Andrus", existingPlayers), position: getPosition("Tyler R. Andrus", existingPlayers), height: getHeight("Tyler R. Andrus", existingPlayers), weight: getWeight("Tyler R. Andrus", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Riley R. Averett", studentId: "9367217", period: "Period 1", grade: getGrade("Riley R. Averett", existingPlayers), position: getPosition("Riley R. Averett", existingPlayers), height: getHeight("Riley R. Averett", existingPlayers), weight: getWeight("Riley R. Averett", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Finn N. Barney", studentId: "9360100", period: "Period 1", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Corbin D. Bauerle", studentId: "9323795", period: "Period 1", grade: getGrade("Corbin D. Bauerle", existingPlayers), position: getPosition("Corbin D. Bauerle", existingPlayers), height: getHeight("Corbin D. Bauerle", existingPlayers), weight: getWeight("Corbin D. Bauerle", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Brady J. Belliston", studentId: "9323820", period: "Period 1", grade: getGrade("Brady J. Belliston", existingPlayers), position: getPosition("Brady J. Belliston", existingPlayers), height: getHeight("Brady J. Belliston", existingPlayers), weight: getWeight("Brady J. Belliston", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Brady K. Benson", studentId: "9359587", period: "Period 1", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Ocean T. Bishop", studentId: "9328608", period: "Period 1", grade: getGrade("Ocean T. Bishop", existingPlayers), position: getPosition("Ocean T. Bishop", existingPlayers), height: getHeight("Ocean T. Bishop", existingPlayers), weight: getWeight("Ocean T. Bishop", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Kenyon W. Bowman", studentId: "9348807", period: "Period 1", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Luke O. Broadbent", studentId: "9392230", period: "Period 1", grade: getGrade("Luke O. Broadbent", existingPlayers), position: getPosition("Luke O. Broadbent", existingPlayers), height: getHeight("Luke O. Broadbent", existingPlayers), weight: getWeight("Luke O. Broadbent", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Robert M. Christensen", studentId: "9323657", period: "Period 1", grade: getGrade("Robert M. Christensen", existingPlayers), position: getPosition("Robert M. Christensen", existingPlayers), height: getHeight("Robert M. Christensen", existingPlayers), weight: getWeight("Robert M. Christensen", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Magnum Clark", studentId: "9310215", period: "Period 1", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Marek J. Clark", studentId: "9361306", period: "Period 1", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Cason K. Davis", studentId: "9342155", period: "Period 1", grade: getGrade("Cason K. Davis", existingPlayers), position: getPosition("Cason K. Davis", existingPlayers), height: getHeight("Cason K. Davis", existingPlayers), weight: getWeight("Cason K. Davis", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Ryan J. Dawson", studentId: "9326340", period: "Period 1", grade: getGrade("Ryan J. Dawson", existingPlayers), position: getPosition("Ryan J. Dawson", existingPlayers), height: getHeight("Ryan J. Dawson", existingPlayers), weight: getWeight("Ryan J. Dawson", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "David B. Dean", studentId: "9323736", period: "Period 1", grade: getGrade("David B. Dean", existingPlayers), position: getPosition("David B. Dean", existingPlayers), height: getHeight("David B. Dean", existingPlayers), weight: getWeight("David B. Dean", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Maxon J. DeGroot", studentId: "9325387", period: "Period 1", grade: getGrade("Maxon J. DeGroot", existingPlayers), position: getPosition("Maxon J. DeGroot", existingPlayers), height: getHeight("Maxon J. DeGroot", existingPlayers), weight: getWeight("Maxon J. DeGroot", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Owen D. Gardner", studentId: "9325795", period: "Period 1", grade: getGrade("Owen D. Gardner", existingPlayers), position: getPosition("Owen D. Gardner", existingPlayers), height: getHeight("Owen D. Gardner", existingPlayers), weight: getWeight("Owen D. Gardner", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Sawyer R. Hayward", studentId: "9325146", period: "Period 1", grade: getGrade("Sawyer R. Hayward", existingPlayers), position: getPosition("Sawyer R. Hayward", existingPlayers), height: getHeight("Sawyer R. Hayward", existingPlayers), weight: getWeight("Sawyer R. Hayward", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Calvin G. Huffaker", studentId: "9473597", period: "Period 1", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Madden S. Jensen", studentId: "9323013", period: "Period 1", grade: getGrade("Madden S. Jensen", existingPlayers), position: getPosition("Madden S. Jensen", existingPlayers), height: getHeight("Madden S. Jensen", existingPlayers), weight: getWeight("Madden S. Jensen", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Maxwell A. Larson", studentId: "9328296", period: "Period 1", grade: getGrade("Maxwell A. Larson", existingPlayers), position: getPosition("Maxwell A. Larson", existingPlayers), height: getHeight("Maxwell A. Larson", existingPlayers), weight: getWeight("Maxwell A. Larson", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Leonidas P. Latu", studentId: "9432628", period: "Period 1", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Kaedin J. Laursen", studentId: "9328297", period: "Period 1", grade: getGrade("Kaedin J. Laursen", existingPlayers), position: getPosition("Kaedin J. Laursen", existingPlayers), height: getHeight("Kaedin J. Laursen", existingPlayers), weight: getWeight("Kaedin J. Laursen", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Ziah A. Leung-Wai", studentId: "9368408", period: "Period 1", grade: getGrade("Ziah A. Leung-Wai", existingPlayers), position: getPosition("Ziah A. Leung-Wai", existingPlayers), height: getHeight("Ziah A. Leung-Wai", existingPlayers), weight: getWeight("Ziah A. Leung-Wai", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Zackary S. Lewis", studentId: "9363592", period: "Period 1", grade: getGrade("Zackary S. Lewis", existingPlayers), position: getPosition("Zackary S. Lewis", existingPlayers), height: getHeight("Zackary S. Lewis", existingPlayers), weight: getWeight("Zackary S. Lewis", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Brayden R. Litke", studentId: "9361210", period: "Period 1", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Madden S. Mack", studentId: "9358172", period: "Period 1", grade: getGrade("Madden S. Mack", existingPlayers), position: getPosition("Madden S. Mack", existingPlayers), height: getHeight("Madden S. Mack", existingPlayers), weight: getWeight("Madden S. Mack", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Derek R. Manning", studentId: "9414684", period: "Period 1", grade: getGrade("Derek R. Manning", existingPlayers), position: getPosition("Derek R. Manning", existingPlayers), height: getHeight("Derek R. Manning", existingPlayers), weight: getWeight("Derek R. Manning", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Kapono R. Manuela", studentId: "9324984", period: "Period 1", grade: getGrade("Kapono R. Manuela", existingPlayers), position: getPosition("Kapono R. Manuela", existingPlayers), height: getHeight("Kapono R. Manuela", existingPlayers), weight: getWeight("Kapono R. Manuela", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Gunner B. Michaelis", studentId: "9325432", period: "Period 1", grade: getGrade("Gunner B. Michaelis", existingPlayers), position: getPosition("Gunner B. Michaelis", existingPlayers), height: getHeight("Gunner B. Michaelis", existingPlayers), weight: getWeight("Gunner B. Michaelis", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Mitt Palmer", studentId: "9327681", period: "Period 1", grade: getGrade("Mitt Palmer", existingPlayers), position: getPosition("Mitt Palmer", existingPlayers), height: getHeight("Mitt Palmer", existingPlayers), weight: getWeight("Mitt Palmer", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Jett J. Prestwich", studentId: "9327365", period: "Period 1", grade: getGrade("Jett J. Prestwich", existingPlayers), position: getPosition("Jett J. Prestwich", existingPlayers), height: getHeight("Jett J. Prestwich", existingPlayers), weight: getWeight("Jett J. Prestwich", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Beckham B. Rees", studentId: "9328071", period: "Period 1", grade: getGrade("Beckham B. Rees", existingPlayers), position: getPosition("Beckham B. Rees", existingPlayers), height: getHeight("Beckham B. Rees", existingPlayers), weight: getWeight("Beckham B. Rees", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Jack Reutzel", studentId: "9310013", period: "Period 1", grade: getGrade("Jack Reutzel", existingPlayers), position: getPosition("Jack Reutzel", existingPlayers), height: getHeight("Jack Reutzel", existingPlayers), weight: getWeight("Jack Reutzel", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Talon K. Roberts", studentId: "9337186", period: "Period 1", grade: getGrade("Talon K. Roberts", existingPlayers), position: getPosition("Talon K. Roberts", existingPlayers), height: getHeight("Talon K. Roberts", existingPlayers), weight: getWeight("Talon K. Roberts", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Jackson K. Theobald.", studentId: "9391317", period: "Period 1", grade: getGrade("Jackson K. Theobald.", existingPlayers), position: getPosition("Jackson K. Theobald.", existingPlayers), height: getHeight("Jackson K. Theobald.", existingPlayers), weight: getWeight("Jackson K. Theobald.", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Carson A. Thorne", studentId: "9462136", period: "Period 1", grade: getGrade("Carson A. Thorne", existingPlayers), position: getPosition("Carson A. Thorne", existingPlayers), height: getHeight("Carson A. Thorne", existingPlayers), weight: getWeight("Carson A. Thorne", existingPlayers), equipment: { ...defaultEquipment } },

  // Period 2 (Sec 002) - 35 students
  { name: "Hiland M. Atwood", studentId: "9353750", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Pharis S. Blackhurst", studentId: "9343692", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Bodee N. Bond", studentId: "9347514", period: "Period 2", grade: getGrade("Bodee N. Bond", existingPlayers), position: getPosition("Bodee N. Bond", existingPlayers), height: getHeight("Bodee N. Bond", existingPlayers), weight: getWeight("Bodee N. Bond", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Noah J. Braithwaite", studentId: "9343748", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Kaden J. Brown", studentId: "9476088", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Porter G. Byers", studentId: "9348151", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Trigg A. Camberlango", studentId: "9347184", period: "Period 2", grade: getGrade("Trigg A. Camberlango", existingPlayers), position: getPosition("Trigg A. Camberlango", existingPlayers), height: getHeight("Trigg A. Camberlango", existingPlayers), weight: getWeight("Trigg A. Camberlango", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Gavin W. Cardwell", studentId: "9349007", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "David E. Chadwick", studentId: "9357210", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Jackson T. Chadwick", studentId: "9348008", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Kyle M. Chatwin", studentId: "9370800", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Lucas M. Codrington", studentId: "9433108", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Preston J. Fairbanks", studentId: "9335123", period: "Period 2", grade: getGrade("Preston J. Fairbanks", existingPlayers), position: getPosition("Preston J. Fairbanks", existingPlayers), height: getHeight("Preston J. Fairbanks", existingPlayers), weight: getWeight("Preston J. Fairbanks", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Manatua J. Fano", studentId: "9348054", period: "Period 2", grade: getGrade("Manatua J. Fano", existingPlayers), position: getPosition("Manatua J. Fano", existingPlayers), height: getHeight("Manatua J. Fano", existingPlayers), weight: getWeight("Manatua J. Fano", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Gavin W. Felix", studentId: "9353407", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Logan J. Fleming", studentId: "9435010", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Warner Gallagher", studentId: "9416437", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Kael T. Gardner", studentId: "9335504", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Mckay J. Gardner", studentId: "9349873", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Carson S. Holladay", studentId: "9346958", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Ty Holmstead", studentId: "9478409", period: "Period 2", grade: getGrade("Ty Holmstead", existingPlayers), position: getPosition("Ty Holmstead", existingPlayers), height: getHeight("Ty Holmstead", existingPlayers), weight: getWeight("Ty Holmstead", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Trey T. Kelsey", studentId: "9349196", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Mac R. Livingston", studentId: "9336732", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Mckay R. Magleby", studentId: "9419424", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Logan Neuenswander", studentId: "9480095", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Tanner K. Nite", studentId: "9402687", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Joshua M. Perry Jr", studentId: "9477289", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Nash D. Ray", studentId: "9361665", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Kamdon R. Shelby", studentId: "9351737", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Cash T. Talese", studentId: "9332298", period: "Period 2", grade: getGrade("Cash T. Talese", existingPlayers), position: getPosition("Cash T. Talese", existingPlayers), height: getHeight("Cash T. Talese", existingPlayers), weight: getWeight("Cash T. Talese", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Owen F. Tipa", studentId: "9354130", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Cash M. Tolboe", studentId: "9348564", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Drake E. Wilson", studentId: "9352501", period: "Period 2", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Ty M. Wilson", studentId: "9348393", period: "Period 2", grade: getGrade("Ty M. Wilson", existingPlayers), position: getPosition("Ty M. Wilson", existingPlayers), height: getHeight("Ty M. Wilson", existingPlayers), weight: getWeight("Ty M. Wilson", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Levi E. Woods", studentId: "9337905", period: "Period 2", grade: getGrade("Levi E. Woods", existingPlayers), position: getPosition("Levi E. Woods", existingPlayers), height: getHeight("Levi E. Woods", existingPlayers), weight: getWeight("Levi E. Woods", existingPlayers), equipment: { ...defaultEquipment } },

  // Period 5 (Sec 005) - 40 students
  { name: "Dalin N. Afu", studentId: "9333389", period: "Period 5", grade: getGrade("Dalin N. Afu", existingPlayers), position: getPosition("Dalin N. Afu", existingPlayers), height: getHeight("Dalin N. Afu", existingPlayers), weight: getWeight("Dalin N. Afu", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Prince Afu", studentId: "9332179", period: "Period 5", grade: getGrade("Prince Afu", existingPlayers), position: getPosition("Prince Afu", existingPlayers), height: getHeight("Prince Afu", existingPlayers), weight: getWeight("Prince Afu", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Blake H. Averett", studentId: "9367208", period: "Period 5", grade: getGrade("Blake H. Averett", existingPlayers), position: getPosition("Blake H. Averett", existingPlayers), height: getHeight("Blake H. Averett", existingPlayers), weight: getWeight("Blake H. Averett", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Noah H. Behm", studentId: "9336032", period: "Period 5", grade: getGrade("Noah H. Behm", existingPlayers), position: getPosition("Noah H. Behm", existingPlayers), height: getHeight("Noah H. Behm", existingPlayers), weight: getWeight("Noah H. Behm", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Matthew A. Bowen", studentId: "9342693", period: "Period 5", grade: getGrade("Matthew A. Bowen", existingPlayers), position: getPosition("Matthew A. Bowen", existingPlayers), height: getHeight("Matthew A. Bowen", existingPlayers), weight: getWeight("Matthew A. Bowen", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Mason R. Brooks", studentId: "9341554", period: "Period 5", grade: getGrade("Mason R. Brooks", existingPlayers), position: getPosition("Mason R. Brooks", existingPlayers), height: getHeight("Mason R. Brooks", existingPlayers), weight: getWeight("Mason R. Brooks", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Braylon T. Carroll", studentId: "9336471", period: "Period 5", grade: getGrade("Braylon T. Carroll", existingPlayers), position: getPosition("Braylon T. Carroll", existingPlayers), height: getHeight("Braylon T. Carroll", existingPlayers), weight: getWeight("Braylon T. Carroll", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Nathan B. Childs", studentId: "9335901", period: "Period 5", grade: getGrade("Nathan B. Childs", existingPlayers), position: getPosition("Nathan B. Childs", existingPlayers), height: getHeight("Nathan B. Childs", existingPlayers), weight: getWeight("Nathan B. Childs", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Collin J. Christensen", studentId: "9336045", period: "Period 5", grade: getGrade("Collin J. Christensen", existingPlayers), position: getPosition("Collin J. Christensen", existingPlayers), height: getHeight("Collin J. Christensen", existingPlayers), weight: getWeight("Collin J. Christensen", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Keagan D. Clegg", studentId: "9359858", period: "Period 5", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Zachary D. Cowie", studentId: "9336674", period: "Period 5", grade: getGrade("Zachary D. Cowie", existingPlayers), position: getPosition("Zachary D. Cowie", existingPlayers), height: getHeight("Zachary D. Cowie", existingPlayers), weight: getWeight("Zachary D. Cowie", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Logan R. Giles", studentId: "9332920", period: "Period 5", grade: getGrade("Logan R. Giles", existingPlayers), position: getPosition("Logan R. Giles", existingPlayers), height: getHeight("Logan R. Giles", existingPlayers), weight: getWeight("Logan R. Giles", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Drew Greenwood", studentId: "9332490", period: "Period 5", grade: getGrade("Drew Greenwood", existingPlayers), position: getPosition("Drew Greenwood", existingPlayers), height: getHeight("Drew Greenwood", existingPlayers), weight: getWeight("Drew Greenwood", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Dayton C. Hansen", studentId: "9336164", period: "Period 5", grade: getGrade("Dayton C. Hansen", existingPlayers), position: getPosition("Dayton C. Hansen", existingPlayers), height: getHeight("Dayton C. Hansen", existingPlayers), weight: getWeight("Dayton C. Hansen", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Nathan S. Higley", studentId: "9476155", period: "Period 5", grade: getGrade("Nathan S. Higley", existingPlayers), position: getPosition("Nathan S. Higley", existingPlayers), height: getHeight("Nathan S. Higley", existingPlayers), weight: getWeight("Nathan S. Higley", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Heneli B. longi", studentId: "9338006", period: "Period 5", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Joshua C. Jackson", studentId: "9336356", period: "Period 5", grade: getGrade("Joshua C. Jackson", existingPlayers), position: getPosition("Joshua C. Jackson", existingPlayers), height: getHeight("Joshua C. Jackson", existingPlayers), weight: getWeight("Joshua C. Jackson", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Rhett Jensen", studentId: "9336577", period: "Period 5", grade: getGrade("Rhett Jensen", existingPlayers), position: getPosition("Rhett Jensen", existingPlayers), height: getHeight("Rhett Jensen", existingPlayers), weight: getWeight("Rhett Jensen", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Carter J. Jorgenson", studentId: "9441692", period: "Period 5", grade: getGrade("Carter J. Jorgenson", existingPlayers), position: getPosition("Carter J. Jorgenson", existingPlayers), height: getHeight("Carter J. Jorgenson", existingPlayers), weight: getWeight("Carter J. Jorgenson", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Dylan S. Latu", studentId: "9432614", period: "Period 5", grade: getGrade("Dylan S. Latu", existingPlayers), position: getPosition("Dylan S. Latu", existingPlayers), height: getHeight("Dylan S. Latu", existingPlayers), weight: getWeight("Dylan S. Latu", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Eikipeavale T. Mausia.", studentId: "9383647", period: "Period 5", grade: getGrade("Eikipeavale T. Mausia.", existingPlayers), position: getPosition("Eikipeavale T. Mausia.", existingPlayers), height: getHeight("Eikipeavale T. Mausia.", existingPlayers), weight: getWeight("Eikipeavale T. Mausia.", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Lincoln M. Miller", studentId: "9336243", period: "Period 5", grade: getGrade("Lincoln M. Miller", existingPlayers), position: getPosition("Lincoln M. Miller", existingPlayers), height: getHeight("Lincoln M. Miller", existingPlayers), weight: getWeight("Lincoln M. Miller", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Jaybian-Damani V. Na'a", studentId: "9407200", period: "Period 5", grade: getGrade("Jaybian-Damani V. Na'a", existingPlayers), position: getPosition("Jaybian-Damani V. Na'a", existingPlayers), height: getHeight("Jaybian-Damani V. Na'a", existingPlayers), weight: getWeight("Jaybian-Damani V. Na'a", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Mathew Nelson", studentId: "9321875", period: "Period 5", grade: getGrade("Mathew Nelson", existingPlayers), position: getPosition("Mathew Nelson", existingPlayers), height: getHeight("Mathew Nelson", existingPlayers), weight: getWeight("Mathew Nelson", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Mason T. Petersen", studentId: "9366693", period: "Period 5", grade: getGrade("Mason T. Petersen", existingPlayers), position: getPosition("Mason T. Petersen", existingPlayers), height: getHeight("Mason T. Petersen", existingPlayers), weight: getWeight("Mason T. Petersen", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Owen T. Peterson", studentId: "9332848", period: "Period 5", grade: getGrade("Owen T. Peterson", existingPlayers), position: getPosition("Owen T. Peterson", existingPlayers), height: getHeight("Owen T. Peterson", existingPlayers), weight: getWeight("Owen T. Peterson", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Parker L. Pulley", studentId: "9336704", period: "Period 5", grade: getGrade("Parker L. Pulley", existingPlayers), position: getPosition("Parker L. Pulley", existingPlayers), height: getHeight("Parker L. Pulley", existingPlayers), weight: getWeight("Parker L. Pulley", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Hayden D. Reutzel", studentId: "9336724", period: "Period 5", grade: getGrade("Hayden D. Reutzel", existingPlayers), position: getPosition("Hayden D. Reutzel", existingPlayers), height: getHeight("Hayden D. Reutzel", existingPlayers), weight: getWeight("Hayden D. Reutzel", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Mack T. Segura", studentId: "9338982", period: "Period 5", grade: getGrade("Mack T. Segura", existingPlayers), position: getPosition("Mack T. Segura", existingPlayers), height: getHeight("Mack T. Segura", existingPlayers), weight: getWeight("Mack T. Segura", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Hudson B. Taylor", studentId: "9329433", period: "Period 5", grade: getGrade("Hudson B. Taylor", existingPlayers), position: getPosition("Hudson B. Taylor", existingPlayers), height: getHeight("Hudson B. Taylor", existingPlayers), weight: getWeight("Hudson B. Taylor", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Samson N. Thompson", studentId: "9354608", period: "Period 5", grade: getGrade("Samson N. Thompson", existingPlayers), position: getPosition("Samson N. Thompson", existingPlayers), height: getHeight("Samson N. Thompson", existingPlayers), weight: getWeight("Samson N. Thompson", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Ryker F. Tippets", studentId: "9337732", period: "Period 5", grade: getGrade("Ryker F. Tippets", existingPlayers), position: getPosition("Ryker F. Tippets", existingPlayers), height: getHeight("Ryker F. Tippets", existingPlayers), weight: getWeight("Ryker F. Tippets", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Tuapasi A. Uluilakepa Jr", studentId: "9341012", period: "Period 5", grade: getGrade("Tuapasi A. Uluilakepa Jr", existingPlayers), position: getPosition("Tuapasi A. Uluilakepa Jr", existingPlayers), height: getHeight("Tuapasi A. Uluilakepa Jr", existingPlayers), weight: getWeight("Tuapasi A. Uluilakepa Jr", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Latani H. Vaki", studentId: "9417282", period: "Period 5", grade: getGrade("Latani H. Vaki", existingPlayers), position: getPosition("Latani H. Vaki", existingPlayers), height: getHeight("Latani H. Vaki", existingPlayers), weight: getWeight("Latani H. Vaki", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Luke S. Vernon", studentId: "9338521", period: "Period 5", grade: getGrade("Luke S. Vernon", existingPlayers), position: getPosition("Luke S. Vernon", existingPlayers), height: getHeight("Luke S. Vernon", existingPlayers), weight: getWeight("Luke S. Vernon", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Xander D. Voeller", studentId: "9467245", period: "Period 5", grade: getGrade("Xander D. Voeller", existingPlayers), position: getPosition("Xander D. Voeller", existingPlayers), height: getHeight("Xander D. Voeller", existingPlayers), weight: getWeight("Xander D. Voeller", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Tayton P. Webster", studentId: "9427319", period: "Period 5", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Damian C. Wilkinson", studentId: "9340733", period: "Period 5", grade: getGrade("Damian C. Wilkinson", existingPlayers), position: getPosition("Damian C. Wilkinson", existingPlayers), height: getHeight("Damian C. Wilkinson", existingPlayers), weight: getWeight("Damian C. Wilkinson", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Talon J. Willardson", studentId: "9336785", period: "Period 5", grade: getGrade("Talon J. Willardson", existingPlayers), position: getPosition("Talon J. Willardson", existingPlayers), height: getHeight("Talon J. Willardson", existingPlayers), weight: getWeight("Talon J. Willardson", existingPlayers), equipment: { ...defaultEquipment } },
  { name: "Jace Worthington", studentId: "9336891", period: "Period 5", grade: getGrade("Jace Worthington", existingPlayers), position: getPosition("Jace Worthington", existingPlayers), height: getHeight("Jace Worthington", existingPlayers), weight: getWeight("Jace Worthington", existingPlayers), equipment: { ...defaultEquipment } },

  // Additional players added manually
  { name: "Kaden Laursen", studentId: "9999001", period: "", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Kosei Nite", studentId: "9999002", period: "", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Kale Gardner", studentId: "9999003", period: "", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Eli Chadwick", studentId: "9999004", period: "", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Tani Vaki", studentId: "9999005", period: "", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Andrew Uluilakepa", studentId: "9999006", period: "", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Suone Uluilakepa", studentId: "9999007", period: "", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "David Lambourne", studentId: "9999008", period: "", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Tavi Luna", studentId: "9999009", period: "", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
  { name: "Kenny Bowman", studentId: "9999010", period: "", grade: "-", position: "", height: "-", weight: "-", equipment: { ...defaultEquipment } },
];
